apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" (include "furniture.fullname" .) }}
  namespace: {{ .Release.Name }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        resources: {{ toYaml .Values.resources | indent 10 }}