apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" (include "furniture.fullname" .) }}
  namespace: {{ .Release.Name }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 4 }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        - name: DB_HOST
          value: {{ if .Values.postgres.enabled }}"{{ include "furniture.fullname" . }}-postgres"{{ else }}"postgres"{{ end }}
        - name: DB_USER
          value: "{{ .Values.postgres.postgresUser }}"
        - name: DB_PASS
          value: "{{ .Values.postgres.postgresPassword }}"
        - name: DB_NAME
          value: "{{ .Values.postgres.postgresDatabase }}"