
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "furniture.fullname" .) }}
  namespace: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" }}
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
spec:
  rules:
  - host: {{ include "furniture.host" . }}
    http:
    paths:
    - path: /api
      pathType: Prefix
      backend:
        service:
          name: {{ printf "%s-backend" (include "furniture.fullname" .) }}
          port:
          number: 4200
    - path: /
      pathType: Prefix
      backend:
        service:
          name: {{ printf "%s-frontend" (include "furniture.fullname" .) }}
          port:
          number: 4200