baseDomain: "test1.sapi2025.camdvr.org" # change to your subdomain

frontend:
  image: ghcr.io/tiborsapi/furniture-frontend
  tag: "latest"
  containerPort: 80
  replicas: 1

backend:
  image: ghcr.io/tiborsapi/furniture-backend
  tag: "latest"
  containerPort: 3000
  replicas: 1

# Ingress settings
ingress:
  enabled: true
  className: "nginx"
  tls: false
  tlsSecretName: ""

podAnnotations: {}
serviceAnnotations: {}

resources: {}